apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: three-tier-role
  namespace: three-tier

rules:

# Pods
- apiGroups: [""]
  resources:
    - pods
    - pods/log
  verbs:
    - get
    - list
    - watch

# Services
- apiGroups: [""]
  resources:
    - services
  verbs:
    - get
    - list
    - watch

# ConfigMaps
- apiGroups: [""]
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch

# Secrets
- apiGroups: [""]
  resources:
    - secrets
  verbs:
    - get

# Deployments
- apiGroups: ["apps"]
  resources:
    - deployments
  verbs:
    - get
    - list
    - watch

# Horizontal Pod Autoscalers
- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch