# Build stage
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

# 🔥 ADD THIS LINE
ENV NODE_OPTIONS=--openssl-legacy-provider

COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
