pipeline {
agent any


environment {
    IMAGE_NAME = "frontend"
    IMAGE_TAG = "${BUILD_NUMBER}"
    ECR_REPO = "588319087110.dkr.ecr.ap-south-1.amazonaws.com/frontend"
}

tools {
    jdk 'jdk17'
    nodejs 'node18'
}

stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Install Dependencies') {
        steps {
            dir('Application-Code/frontend') {
                sh 'npm install'
            }
        }
    }

    stage('SonarQube Scan') {
        steps {
            dir('Application-Code/frontend') {
                withSonarQubeEnv('sonar-server') {
                    sh '''
                    sonar-scanner \
                    -Dsonar.projectKey=frontend \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=$SONAR_HOST_URL \
                    -Dsonar.login=$SONAR_AUTH_TOKEN
                    '''
                }
            }
        }
    }

    stage('OWASP Dependency Check') {
        steps {
            dependencyCheck additionalArguments: '--scan Application-Code/frontend'
        }
    }

    stage('OWASP Report Publish') {
        steps {
            dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
        }
    }

    stage('Build Docker Image') {
        steps {
            dir('Application-Code/frontend') {
                sh '''
                docker build -t frontend:${BUILD_NUMBER} .
                '''
            }
        }
    }

    stage('Trivy Scan') {
        steps {
            sh '''
            trivy image --exit-code 0 frontend:${BUILD_NUMBER}
            '''
        }
    }

    stage('ECR Login') {
        steps {
            sh '''
            aws ecr get-login-password --region ap-south-1 | \
            docker login --username AWS \
            --password-stdin 588319087110.dkr.ecr.ap-south-1.amazonaws.com
            '''
        }
    }

    stage('Push Image') {
        steps {
            sh '''
            docker tag frontend:${BUILD_NUMBER} ${ECR_REPO}:${BUILD_NUMBER}
            docker push ${ECR_REPO}:${BUILD_NUMBER}
            '''
        }
    }
}

post {
    always {
        cleanWs()
    }

    success {
        echo 'Frontend Pipeline Completed Successfully'
    }

    failure {
        echo 'Frontend Pipeline Failed'
    }
}


}
