community:
  enabled: true

sonarWebContext: /sonarqube

monitoringPasscode: sonar123

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: gp2

postgresql:
  enabled: true
  auth:
    database: sonarqube
    username: sonar
    password: sonar

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 4Gi

service:
  type: ClusterIP