apiVersion: v1

kind: Secret


metadata:

  name: app-secret

  namespace: three-tier-app


type: Opaque


stringData:

  MONGO_USERNAME: admin

  MONGO_PASSWORD: admin123

  MONGO_DATABASE: three-tier-app
