apiVersion: v1
kind: Secret

metadata:
  name: mongodb-secret
  namespace: production

type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password123

---
apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: production

type: Opaque

stringData:
  MONGO_URI: mongodb://admin:password123@mongodb-service:27017/mern?authSource=admin
  JWT_SECRET: my-super-secret-jwt-key