---
# -------------------------
# Ansible
# -------------------------
ansible_user: ubuntu
ansible_become: true

# -------------------------
# Docker
# -------------------------
docker_users:
  - ubuntu
  - jenkins

# -------------------------
# Java
# -------------------------
java_package: openjdk-21-jre

# -------------------------
# Jenkins
# -------------------------
jenkins_port: 8080
jenkins_admin_user: admin
jenkins_admin_password: Admin@123

# -------------------------
# Kubernetes
# -------------------------
kubectl_version: "v1.31.0"

# -------------------------
# Helm
# -------------------------
helm_version: "v3.18.4"

# -------------------------
# Monitoring
# -------------------------
monitoring_namespace: monitoring

# -------------------------
# AWS Region
# -------------------------
aws_region: ap-south-1