pipeline {
    agent any

    environment {
        IMAGE_NAME = "backend"
        AWS_REGION = "ap-south-1"
    }

    tools {
        jdk 'jdk17'
        nodejs 'NodeJS 18'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/ayareanuja0903-collab/End-to-End-Kubernetes-Three-Tier-DevSecOps-MERN-Stack-Project.git'
            }
        }

        stage('Skip Jenkins Commit') {
            steps {
                script {
                    def commitMsg = sh(
                        script: "git log -1 --pretty=%B",
                        returnStdout: true
                    ).trim()

                    if (commitMsg.contains('[skip ci]')) {
                        currentBuild.result = 'SUCCESS'
                        error('Skipping Jenkins generated commit')
                    }
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Application-Code/backend') {
                    sh 'npm install'
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                dir('Application-Code/backend') {
                    withSonarQubeEnv('sonar-server') {
                        sh """
                        ${tool 'sonar-scanner'}/bin/sonar-scanner \
                        -Dsonar.projectKey=backend \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=$SONAR_HOST_URL \
                        -Dsonar.login=$SONAR_AUTH_TOKEN
                        """
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Application-Code/backend') {
                    sh """
                    docker build -t backend:${BUILD_NUMBER} .
                    """
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                sh """
                trivy image --exit-code 0 backend:${BUILD_NUMBER}
                """
            }
        }

        stage('Push Image To ECR') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds']
                ]) {
                    sh '''
                    ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

                    ECR_REPO=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend

                    aws ecr get-login-password --region $AWS_REGION | \
                    docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

                    docker tag backend:${BUILD_NUMBER} $ECR_REPO:${BUILD_NUMBER}

                    docker push $ECR_REPO:${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Update Deployment Manifest') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'github-creds',
                        usernameVariable: 'GIT_USER',
                        passwordVariable: 'GIT_TOKEN'
                    ),
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-creds'
                    ]
                ]) {

                    sh '''
                    git checkout main

                    ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

                    IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend:${BUILD_NUMBER}

                    sed -i "s|image: .*|image: $IMAGE_URI|g" k8s/backend-deployment.yaml

                    echo "Updated Manifest:"
                    cat k8s/backend-deployment.yaml

                    git config --global user.email "jenkins@local"
                    git config --global user.name "jenkins"

                    git add k8s/backend-deployment.yaml

                    if ! git diff --cached --quiet; then
                        git commit -m "[skip ci] Update backend image ${BUILD_NUMBER}"
                    fi

                    git remote set-url origin https://${GIT_USER}:${GIT_TOKEN}@github.com/ayareanuja0903-collab/End-to-End-Kubernetes-Three-Tier-DevSecOps-MERN-Stack-Project.git

                    # Get latest changes from GitHub
                    git fetch origin main

                    # Rebase our commit on top of latest main
                    git rebase origin/main || {
                        git rebase --abort
                        exit 1
                    }

                    git push origin HEAD:main
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }

        success {
            echo 'Backend Pipeline Completed Successfully'
        }

        failure {
            echo 'Backend Pipeline Failed'
        }
    }
}