apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  MONGO_HOST: {{ .Values.config.mongoHost | quote }}
  MONGO_PORT: {{ .Values.config.mongoPort | quote }}
  BACKEND_URL: {{ .Values.config.backendUrl | quote }}
