apiVersion: v1
kind: Secret

metadata:
  name: app-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

type: Opaque

stringData:
  MONGO_USERNAME: {{ .Values.secret.mongoUsername | quote }}
  MONGO_PASSWORD: {{ .Values.secret.mongoPassword | quote }}
  MONGO_DATABASE: {{ .Values.secret.mongoDatabase | quote }}
