apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  type: ExternalName
  externalName: backend-service.three-tier-app.svc.cluster.local

  selector:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
