apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: three-tier-app
  labels:
    app: backend

spec:

  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      serviceAccountName: three-tier-sa

      containers:

      - name: backend

        image: 023465168943.dkr.ecr.ap-south-1.amazonaws.com/three-tier-dev-backend:latest

        imagePullPolicy: Always

        ports:

        - containerPort: 5000


        env:

        - name: NODE_ENV
          value: "production"


        - name: PORT
          value: "5000"


        # IMPORTANT:
        # Your backend db.js reads process.env.MONGO_CONN_STR
        - name: MONGO_CONN_STR
          value: "mongodb://mongodb-service:27017/three-tier-app"


        # MongoDB authentication disabled
        - name: USE_DB_AUTH
          value: "false"


        resources:

          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"


        readinessProbe:

          httpGet:
            path: /
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 10


        livenessProbe:

          httpGet:
            path: /
            port: 5000

          initialDelaySeconds: 30
          periodSeconds: 20
