---
- name: Common Configuration
  hosts: all
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist

    - name: Install common packages
      apt:
        name:
          - curl
          - wget
          - unzip
          - git
          - vim
          - nano
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
        state: present