---
- name: Run SonarQube Docker Container
  hosts: jenkins
  become: yes

  tasks:

    - name: Pull SonarQube Image
      docker_image:
        name: sonarqube:lts-community
        source: pull

    - name: Start SonarQube
      docker_container:
        name: sonarqube
        image: sonarqube:lts-community
        state: started
        restart_policy: always
        ports:
          - "9000:9000"