---
- name: Install Trivy
  hosts: jenkins
  become: yes

  tasks:

    - name: Add Trivy Key
      apt_key:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present

    - name: Add Repository
      apt_repository:
        repo: "deb https://aquasecurity.github.io/trivy-repo/deb generic main"
        state: present

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Trivy
      apt:
        name: trivy
        state: present

    - name: Verify Trivy
      command: trivy --version
      register: trivy_version

    - debug:
        var: trivy_version.stdout