grafana:
  enabled: true

  adminUser: admin
  adminPassword: Admin@123

  service:
    type: ClusterIP

  persistence:
    enabled: true
    storageClassName: gp3
    size: 10Gi

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/"

prometheus:
  enabled: true

  service:
    type: ClusterIP

alertmanager:
  enabled: true

  service:
    type: ClusterIP

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true