grafana:
  enabled: true

  adminUser: admin
  adminPassword: Admin@123

  service:
    type: ClusterIP

  persistence:
    enabled: true
    storageClassName: gp2
    size: 10Gi

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true

prometheus:
  enabled: true

  prometheusSpec:
    retention: 15d

    scrapeInterval: 30s

    evaluationInterval: 30s

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi