global:
  domain: ""

server:
  service:
    type: ClusterIP

  ingress:
    enabled: false

  extraArgs:
    - --insecure
    - --rootpath=/argocd
    - --basehref=/argocd

configs:
  params:
    server.insecure: "true"

  cm:
    argocd_url = "http://${aws_lb.platform.dns_name}/argocd"

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

redis:
  enabled: true

dex:
  enabled: false

notifications:
  enabled: false