apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config

data:
  MONGO_HOST: "{{ .Values.mongodb.host }}"
  MONGO_PORT: "{{ .Values.mongodb.port }}"
  DATABASE_NAME: "{{ .Values.mongodb.database }}"